"""resize embedding vector

Revision ID: 158757f21730
Revises: f87bd8281f91
Create Date: 2026-07-01 20:13:23.192628

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '158757f21730'
down_revision: str | Sequence[str] | None = 'f87bd8281f91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
