"""Add WatchChannel model

Revision ID: 25417a17905b
Revises: 3ab66c7c83fd
Create Date: 2026-08-15 13:01:16.198342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25417a17905b'
down_revision: Union[str, Sequence[str], None] = '3ab66c7c83fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('channel_token', sa.String(length=255), nullable=False),
    sa.Column('expiration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_token', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_channels_channel_id'), 'watch_channels', ['channel_id'], unique=True)
    op.create_index(op.f('ix_watch_channels_id'), 'watch_channels', ['id'], unique=False)
    op.create_index(op.f('ix_watch_channels_user_id'), 'watch_channels', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_channels_user_id'), table_name='watch_channels')
    op.drop_index(op.f('ix_watch_channels_id'), table_name='watch_channels')
    op.drop_index(op.f('ix_watch_channels_channel_id'), table_name='watch_channels')
    op.drop_table('watch_channels')
    # ### end Alembic commands ###
