"""add expires_at to documents

Revision ID: 3ab66c7c83fd
Revises: 8e223e3448df
Create Date: 2026-08-05 22:29:53.098979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab66c7c83fd'
down_revision: Union[str, Sequence[str], None] = '8e223e3448df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'expires_at')
    # ### end Alembic commands ###
