"""add_cron_expression_to_scheduled_jobs

Revision ID: 442e54d2f95b
Revises: fe3b59645e76
Create Date: 2026-07-09 17:39:12.873388

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '442e54d2f95b'
down_revision: str | Sequence[str] | None = 'fe3b59645e76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_jobs', sa.Column('cron_expression', sa.String(length=50), nullable=True))
    op.add_column('scheduled_jobs', sa.Column('recurring_action', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_jobs', 'recurring_action')
    op.drop_column('scheduled_jobs', 'cron_expression')
    # ### end Alembic commands ###
