"""oauth

Revision ID: 64d85cab085d
Revises: e11624f7a437
Create Date: 2026-07-03 16:21:29.634974

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '64d85cab085d'
down_revision: str | Sequence[str] | None = 'e11624f7a437'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
