"""add_location_tags_to_reminders

Revision ID: 9998a62ae490
Revises: dddc8dff948c
Create Date: 2026-07-09 18:02:29.892103

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9998a62ae490'
down_revision: str | Sequence[str] | None = 'dddc8dff948c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('reminders', sa.Column('location_lon', sa.Float(), nullable=True))
    op.add_column('reminders', sa.Column('location_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'location_name')
    op.drop_column('reminders', 'location_lon')
    op.drop_column('reminders', 'location_lat')
    # ### end Alembic commands ###
