"""add chunk embeddings

Revision ID: f87bd8281f91
Revises: 1289d90976a4
Create Date: 2026-07-01 19:15:29.413592

"""
from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f87bd8281f91'
down_revision: str | Sequence[str] | None = '1289d90976a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding', Vector(3072), nullable=True))
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=True)
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
