"""add_person_habit_temporal

Revision ID: fe3b59645e76
Revises: d1c4dbb04d19
Create Date: 2026-07-09 17:05:13.078899

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fe3b59645e76'
down_revision: str | Sequence[str] | None = 'd1c4dbb04d19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('frequency_target', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_id'), 'habits', ['id'], unique=False)
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('notes_summary', sa.Text(), nullable=True),
    sa.Column('last_mentioned', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_id'), 'people', ['id'], unique=False)
    op.create_index(op.f('ix_people_user_id'), 'people', ['user_id'], unique=False)
    op.create_table('habit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_logs_habit_id'), 'habit_logs', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_logs_id'), 'habit_logs', ['id'], unique=False)
    op.create_table('person_memory',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'memory_id')
    )
    op.create_table('person_note',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'note_id')
    )
    op.add_column('memories', sa.Column('previous_value', sa.String(length=500), nullable=True))
    op.add_column('memories', sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('memories', sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('images', sa.JSON(), nullable=True))
    op.alter_column('reminders', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('reminders', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('reminders', 'snooze_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scheduled_jobs', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scheduled_jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scheduled_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scheduled_jobs', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reminders', 'snooze_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reminders', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('reminders', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('messages', 'images')
    op.drop_column('memories', 'valid_to')
    op.drop_column('memories', 'valid_from')
    op.drop_column('memories', 'previous_value')
    op.drop_table('person_note')
    op.drop_table('person_memory')
    op.drop_index(op.f('ix_habit_logs_id'), table_name='habit_logs')
    op.drop_index(op.f('ix_habit_logs_habit_id'), table_name='habit_logs')
    op.drop_table('habit_logs')
    op.drop_index(op.f('ix_people_user_id'), table_name='people')
    op.drop_index(op.f('ix_people_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_index(op.f('ix_habits_id'), table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
